name: Backend Deploy to Firebase Functions

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發此工作流程。

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用最新版本的 Ubuntu 作為執行環境。

    steps:
      # 1. 檢出代碼（Checkout code）
      - name: Checkout code
        uses: actions/checkout@v3  # 將當前分支的代碼檢出到工作環境。

      # 2. 設置 Node.js 環境（Set up Node.js）
      - name: Set up Node.js
        uses: actions/setup-node@v3  # 使用官方的 Node.js 環境設置工具。
        with:
          node-version: 20  # 指定使用的 Node.js 版本。

      # 3. 安裝 Firebase CLI（Install Firebase CLI）
      - name: Install Firebase CLI
        run: npm install -g firebase-tools  # 全域安裝 Firebase CLI，以便後續使用。

      # 4. 設置 Firebase 認證（Set up Firebase authentication）
      - name: Set up Firebase authentication
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/firebase-key.json
        shell: bash

      # 5. 測試 Firebase 認證（Test Firebase Authentication）
      - name: Test Firebase Authentication
        run: firebase projects:list --json
        shell: bash
        continue-on-error: true  # 即使失敗也繼續，方便檢查輸出。

      # 6. 安裝後端依賴項（Install dependencies）
      - name: Install dependencies
        run: |
          cd functions  # 進入 functions 資料夾。
          npm install  # 安裝 functions 目錄中的所有依賴項。

      # 7. 部署到 Firebase（Deploy to Firebase）
      - name: Deploy to Firebase
        run: |
          cd functions  # 確保位於 functions 目錄。
          firebase deploy --only functions --project your-project-id  # 部署 Firebase Functions。