name: Firebase Functions Deployment

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發此工作流程

jobs:
  deploy-functions:
    name: Deploy Functions
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
      checks: write
      deployments: write
      issues: write
      discussions: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    env:
      PROJECT_ID: sideproject2405-b8a66
      GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Set environment
        run: |
          echo "PROJECT_ID=${{ env.PROJECT_ID }}" >> "$GITHUB_ENV"
          echo "GCP_SA_KEY=${{ env.GCP_SA_KEY }}" >> "$GITHUB_ENV"

      # 1. 檢出代碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 設置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 根據您的專案設定 Node.js 版本

      # 3. 安裝 Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4. 安裝專案依賴
      - name: Install dependencies
        run: |
          cd functions
          npm install
          cd ..

      # 5. 進行身份驗證
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ env.GCP_SA_KEY }}'

      # 6. 部署 Firebase Functions
      - name: Deploy Functions
        run: firebase deploy --only functions --project ${{ env.PROJECT_ID }}