name: Firebase Functions Deployment

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發此工作流程

jobs:
  deploy-functions:
    name: Deploy Functions
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
      checks: write
      deployments: write
      issues: write
      discussions: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    env:
      PROJECT_ID: sideproject2405-b8a66

    steps:
      # 1. 檢出代碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 設置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. 安裝 Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4. 創建 serviceAccountKey.json 文件
      - name: Create serviceAccountKey.json
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' > ./functions/config/serviceAccountKey.json

      # 5. 安裝專案依賴
      - name: Install dependencies
        run: |
          cd functions
          npm install
          cd ..

      # 6. 進行身份驗證
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'

      # 7. 部署 Firebase Functions
      - name: Deploy Functions
        run: firebase deploy --only functions --project ${{ env.PROJECT_ID }}
        
      # 8. 清理多餘的構建映像
      - name: Clean up build images
        run: |
          gcloud container images list --repository="us.gcr.io/${{ env.PROJECT_ID }}" | \
          grep "gcf" | \
          xargs -I {} gcloud container images delete --quiet {} --force